site_name: notebookinit

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      title: On this page

plugins:
  - search:
      lang: en

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
  palette:
    scheme: default
    primary: grey
    accent: deep orange
